NqhK22CNTLesson11/NqhK22CNTLesson11/Controllers/NqhCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NqhK22CNTLesson11.Controllers
{
    public class NqhCategoriesController : Controller
    {
        private NqhK22CNTLesson11Entities db = new NqhK22CNTLesson11Entities();

        // GET: NqhCategories
        public ActionResult NqhIndex()
        {
            return View(db.NqhCategories.ToList());
        }

        // GET: NqhCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NqhCategory nqhCategory = db.NqhCategories.Find(id);
            if (nqhCategory == null)
            {
                return HttpNotFound();
            }
            return View(nqhCategory);
        }

        // GET: NqhCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NqhCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NqhID,NqhCateName,NqhStatus")] NqhCategory nqhCategory)
        {
            if (ModelState.IsValid)
            {
                db.NqhCategories.Add(nqhCategory);
                db.SaveChanges();
                return RedirectToAction("NqhIndex");
            }

            return View(nqhCategory);
        }

        // GET: NqhCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NqhCategory nqhCategory = db.NqhCategories.Find(id);
            if (nqhCategory == null)
            {
                return HttpNotFound();
            }
            return View(nqhCategory);
        }

        // POST: NqhCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NqhID,NqhCateName,NqhStatus")] NqhCategory nqhCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nqhCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("NqhIndex");
            }
            return View(nqhCategory);
        }

        // GET: NqhCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NqhCategory nqhCategory = db.NqhCategories.Find(id);
            if (nqhCategory == null)
            {
                return HttpNotFound();
            }
            return View(nqhCategory);
        }

        // POST: NqhCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NqhCategory nqhCategory = db.NqhCategories.Find(id);
            db.NqhCategories.Remove(nqhCategory);
            db.SaveChanges();
            return RedirectToAction("NqhIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NqhK22CNTLesson11/NqhK22CNTLesson11/Controllers/NqhHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NqhK22CNTLesson11.Controllers
{
    public class NqhHomeController : Controller
    {
        public ActionResult NqhIndex()
        {
            return View();
        }

        public ActionResult NqhAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult NqhContact()
        {
            ViewBag.MSV = "2210900105";
            ViewBag.FullName = "Nquyễn quang Huy";  

            return View();
        }
    }
}

NqhK22CNTLesson11/NqhK22CNTLesson11/Views/Shared/_Nqh2210900105Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nguyễn Quang Huy", "NqhIndex", "NqhHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "NqhIndex", "NqhHome")</li>
                    <li>@Html.ActionLink("About", "NqhAbout", "NqhHome")</li>
                    <li>@Html.ActionLink("Contact", "NqhContact", "NqhHome")</li>

                    <li>@Html.ActionLink("Category", "NqhIndex", "NqhCategories")</li>
                    <li>@Html.ActionLink("Product", "NqhIndex", "NqhHome")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nguyễn Quang Huy </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>