nqh_lesson04/nqh_lesson04/Models/Nqh.Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace nqh_lesson04.Models
{
    public class NqhCustomer
    {
        public int CustomerId { get; set; }
        public string FistName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int YearOfbirth { get; set; }
    }
}

nqh_lesson04/nqh_lesson04/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nqh_lesson04.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

nqh_lesson04/nqh_lesson04/Controllers/NqhCustomerController.cs
using nqh_lesson04.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nqh_lesson04.Controllers
{
    public class NqhCustomerController : Controller
    {
        // GET: NqhCustomer
        public ActionResult Index()
        {
            return View();
        }

        // Action: NqhCustomerDetail
        public ActionResult NqhCustomerDetail()
        {
            // Tạo đối tượng dữ liệu
            var customer = new NqhCustomer()
            {
                CustomerId = 1,
                FistName = "Nguyễn Quang",
                LastName = "Huy",
                Address = "K22CNT4",
                YearOfbirth = 2004
            };
            ViewBag.customer = customer;
            return View();
        }

        // GET: NqhListCustomer
        public ActionResult NqhListCustomer()
        {
            var list = new List<NqhCustomer>()
            {
                new NqhCustomer()
                {
                    CustomerId = 1,
                    FistName = "Nguyễn Quang",
                    LastName = "Huy",
                    Address = "K22CNT4",
                    YearOfbirth = 2004
                },
                new NqhCustomer()
                {
                    CustomerId=2,
                    FistName="Nguyễn Văn",
                    LastName="Hiếu",
                    Address="K22CNT4",
                    YearOfbirth = 2004
                },
                new NqhCustomer()
                {
                    CustomerId=3,
                    FistName="Nguyễn Văn",
                    LastName="Hiếu",
                    Address="K22CNT4",
                    YearOfbirth = 2004
                },
            };
            ViewBag.list = list; // Đưa dữ liệu ra view bằng đối tượng ViewBag

            return View(list);
        }
    }
}

nqh_lesson04/nqh_lesson04/Controllers/NqhCustomerScaffdingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nqh_lesson04.Models;

namespace nqh_lesson04.Controllers
{
    public class NqhCustomerScaffdingController : Controller
    {
        //mockdata
        private List<NqhCustomer> listCustomer = new List<NqhCustomer>()
            {
                new NqhCustomer()
                {
                    CustomerId = 1,
                    FistName = "Nguyễn Quang",
                    LastName = "Huy",
                    Address = "K22CNT4",
                    YearOfbirth = 2004
                },
                new NqhCustomer()
                {
                    CustomerId=2,
                    FistName="Nguyễn Văn",
                    LastName="Hiếu",
                    Address="K22CNT4",
                    YearOfbirth = 2004
                },
                new NqhCustomer()
                {
                    CustomerId=3,
                    FistName="Nguyễn Văn",
                    LastName="Hiếu",
                    Address="K22CNT4",
                    YearOfbirth = 2004
                },
            };

        // GET: NqhCustomerScaffding
        public ActionResult Index()
        {
            return View();
        }
    }
}

nqh_lesson04/nqh_lesson04/Views/NqhCustomer/NqhCustomerDetail.cshtml
@{
    ViewBag.Title = "NqhCustomerDetail";
}

<h2>Thông tin khách hàng</h2>

<div class="alert alert-danger">
    <p>Mã số: @ViewBag.customer.CustomerId</p>
    <p>Họ và tên: @ViewBag.customer.FistName @ViewBag.customer.LastName</p>
    <p>Mã số: @ViewBag.customer.Address</p>
    <p>Mã số: @ViewBag.customer.YearOfbirth</p>
</div>

nqh_lesson04/nqh_lesson04/Views/NqhCustomer/NqhListCustomer.cshtml
@model List<nqh_lesson04.Models.NqhCustomer>
@{
    ViewBag.Title = "NqhListCustomer";
    //var list = ViewBag.list;
    //var list = Model as List<nqh_lesson04.Models.NqhCustomer>;
    int stt = 0;

}
<h2>Danh sách khách hàng</h2>
<div class="row">
     <table class="table table-bordered">
         <thead>
             <tr>
                 <th>#</th>
                 <th>Mã Số</th>
                 <th>Địa Chỉ</th>
                 <th>Năm sinh</th>
                 <th>Chức năng</th>
             </tr>
         </thead>
         <tbody>
             @*@foreach (var item in list)*@
             @foreach (var item in Model)
             {
                 stt++;
                 <tr>
                     <td>@stt</td>
                     <td>@item.CustomerId</td>
                     <td>@item.FistName @item.LastName</td>
                     <td>@item.Address</td>
                     <td>@item.YearOfbirth</td>
                     <td>
                         <a href="#">Edit</a>
                         <a href="#">Delete</a>
                     </td>
                 </tr>
             }

         </tbody>
     </table>

</div>

nqh_lesson04/nqh_lesson04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("List Customer", "NqhListCustomer", "NqhCustomer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Detail Customer", "NqhCustomerDetail", "NqhCustomer", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>